version: '3.8'
services:
  web:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      JWT_SECRET: ${JWT_SECRET}